# misc
notifications:
  email: false
sudo: false

# python settings
language: python
python:
  - "3.7"

# for use in linting and static analysis
env:
  - SOURCES="playtest pt-blackjack examples setup.py"

jobs:
  include:
    - install: pipenv install
      script: flake8 $SOURCES
    - install: pip install -r reqs/lint.txt
      script: black --check $SOURCES

# install packages
install:
  - pip install pipenv
  - pipenv install

# run test
script:
  - pytest --cov=playtest
